export const INTRADAY_AUTO_PORTFOLIO_COPY = {
  title: "AI 자동 단타",
  description: "금액만 정하면 수급·거래량 상위 종목을 조합해 오늘의 모의 포트폴리오를 운용해요.",
  cashLabel: "투자금",
  cashAria: "자동 단타 투자금",
  start: "자동 모의매매 시작",
  starting: "종목별 AI 첫 판단 중…",
  running: "자동 모의매매 실행 중",
  runningDescription: "5분마다 AI가 다시 판단해 모의 매수·매도하고 있어요.",
  completed: "최근 자동 모의매매",
  startDisabled: "실행 중인 자동 모의매매를 종료한 뒤 새로 시작할 수 있어요.",
  loadingTrades: "최신 체결 상태를 불러오고 있어요.",
  waiting: "아직 체결 없이 다음 판단을 기다리고 있어요.",
  noPosition: "현재 보유 없음",
  holding: (quantity: number, price: string) => `${quantity}주 보유 · 평균 ${price}원`,
  latestBuy: (quantity: number, price: string) => `최근 매수 ${quantity}주 · ${price}원`,
  latestSell: (quantity: number, price: string) => `최근 매도 ${quantity}주 · ${price}원`,
  realized: (value: string) => `실현손익 ${value}원`,
  complete: "자동매매 종료",
  completing: "보유 종목 청산 중…",
  completeConfirmTitle: "자동매매를 종료할까요?",
  completeConfirmDescription:
    "보유 중인 모든 종목을 최신 가격으로 모의 전량 매도하고 자동 판단을 종료해요.",
  completeConfirmAction: "전량 매도 후 종료",
  completeCancel: "계속 운용",
  completeError: "자동매매를 종료하지 못했어요. 미청산 종목을 확인한 뒤 다시 시도해 주세요.",
  rule: "상위 후보 중 3~5종목을 자동 선정하고 10%는 현금으로 남겨요. 5분마다 AI가 판단하며 15:40에 자동 종료돼요.",
  startError: "자동 모의매매를 시작하지 못했어요. 잠시 후 다시 시도해 주세요.",
  metrics: {
    stocks: "운용 종목",
    running: (count: number) => `${count}개 자동 운용 중`,
    initial: "시작 투자금",
    value: "현재 평가금",
    return: "포트폴리오 수익률",
  },
} as const;
