export const INTRADAY_GUIDE_COPY = {
  eyebrow: "오늘 하루 이용권",
  title: "AI 단타 가이드",
  subtitle: "상위 거래·수급 종목을 살펴보고, 지금 확인할 매수·매도 가이드를 알려드려요.",
  price: "9,900원",
  trial: "결제 연동 전 체험",
  benefits: ["장중 10분마다 후보 분석", "한 번에 최대 3종목", "오후 3시 40분 자동 종료"],
  capitalLabel: "가이드 기준 금액",
  capitalHint: "종목별 추천 수량을 계산할 때만 사용해요.",
  start: "오늘 가이드 시작하기",
  starting: "가이드를 준비하고 있어요",
  researchRunning: "모의투자 수집 중",
  researchRunningHint: "데이터 수집용 모의투자가 진행 중이에요. 종료 후 가이드를 시작할 수 있어요.",
  startError: "가이드를 시작하지 못했어요. 잠시 후 다시 시도해 주세요.",
  minimumCapital: "기준 금액은 100만 원 이상 입력해 주세요.",
  disclaimer: "실제 주문이나 수익을 보장하지 않아요. 매매 결정과 주문은 사용자가 직접 진행해요.",
  running: "가이드 진행 중",
  stopped: "오늘 가이드가 종료됐어요",
  nextAnalysis: "다음 후보 분석",
  watchedStocks: "분석 종목",
  holdings: "수행 중 보유",
  waitingCount: (count: number) => `대기 ${count}건`,
  stop: "오늘 가이드 종료",
  stopping: "종료 중",
  stopError: "가이드를 종료하지 못했어요.",
  guideEyebrow: "지금 확인할 가이드",
  buy: "매수 가이드",
  sell: "매도 가이드",
  buyAction: "매수했어요",
  sellAction: "매도했어요",
  pass: "이번엔 넘길게요",
  responding: "저장 중",
  responseError: "응답을 저장하지 못했어요. 다시 시도해 주세요.",
  confirmTitle: (side: "BUY" | "SELL") =>
    side === "BUY" ? "이 내용대로 매수했나요?" : "이 내용대로 매도했나요?",
  confirmBody: "확정하면 오늘 가이드 보유 기록에 반영되고 되돌릴 수 없어요.",
  confirm: "네, 수행했어요",
  cancel: "다시 볼게요",
  priceLabel: "기준가",
  quantityLabel: "수량",
  amountLabel: "예상 금액",
  stopLossLabel: "손절 기준",
  targetLabel: "목표가",
  waitingTitle: "상위 거래·수급 종목을 분석하고 있어요",
  waitingBody: "새 가이드가 생기면 이곳에 가장 먼저 보여드릴게요.",
  holdingTitle: "내가 수행한 보유",
  holdingEmpty: "수행한 매수가 생기면 매도 시점을 이어서 알려드려요.",
  averagePrice: "평균",
  activityTitle: "오늘 가이드 기록",
  activityEmpty: "아직 기록이 없어요.",
  performed: "수행함",
  passed: "패스",
  pending: "확인 대기",
  originalNotice: "AI의 가상 체결과 내가 수행한 기록은 별도로 관리돼요.",
  completedBody: "오늘 수행한 기록은 그대로 남아 있어요. 내일 새 가이드를 시작할 수 있어요.",
} as const;
