export const MISTAKE_NOTE_DASHBOARD_COPY = {
  title: "AI 단타 오답노트",
  subtitle: "실제 체결과 반사실 진단을 분리해, 다음 장에 쓸 짧은 규칙만 남겨요.",
  localOnly: "로컬 전용",
  autoRefresh: "장중 30초 자동 갱신",
  refresh: "지금 갱신",
  refreshing: "갱신 중",
  back: "단타 워크스페이스",
  latestDate: "최근 분석일",
  netReturn: "비용 후 일수익",
  actualWinLoss: "실제 W/L",
  memoryRules: "Compact Memory",
  goalZone: "관찰 목표 구간 +1~2% · 수익 보장 아님",
  evidenceTitle: "근거를 섞지 않는 3개 층",
  actualTitle: "1. 실제 체결",
  actualDescription: "비용 후 순손익과 round-trip이 최종 판정 근거예요.",
  counterfactualTitle: "2. 반사실 BUY",
  counterfactualDescription: "놓친 진입·진입 원인 탐색용이며 실제 승률과 합치지 않아요.",
  selectionTitle: "3. 종목 선정",
  selectionDescription: "미선정 후보의 같은 horizon 성과가 있을 때만 lift를 판정해요.",
  rulesTitle: "다음 장에 주입되는 핵심 규칙",
  rulesEmpty: "아직 Compact Memory 규칙이 없어요.",
  historyTitle: "일별 오답노트",
  processTitle: "장 마감 최신화 루프",
  validationOk: "산출물 검증 통과",
  validationError: "산출물 점검 필요",
  noData: "아직 생성된 일별 source가 없어요. 장 마감 후 review를 실행해 주세요.",
} as const;
