export const INTRADAY_RESEARCH_AUTOPILOT_COPY = {
  title: "AI 모의투자 데이터 수집",
  description: "상위 거래·수급 종목을 자동으로 골라 장중 판단과 가상 체결을 계속 기록해요.",
  badge: "오답노트용",
  start: "모의투자 시작",
  starting: "모의투자를 준비하고 있어요",
  stop: "모의투자 중지",
  stopping: "중지 중",
  stopConfirmTitle: "모의투자 수집을 중지할까요?",
  stopConfirmBody: "진행 중인 모의 포지션을 최신 가격으로 전량 청산하고 오늘 데이터 수집을 종료해요.",
  stopConfirmAction: "전량 청산 후 중지",
  stopCancel: "계속 수집",
  stopError: "모의투자를 중지하지 못했어요. 잠시 후 다시 시도해 주세요.",
  running: "장중 데이터 수집 중",
  runningBody: "종목 선정·AI 판단·가상 매수와 매도가 장 마감까지 자동으로 기록돼요.",
  guideRunning: "가이드 실행 중에도 같은 모의투자 원장이 함께 쌓이고 있어요.",
  capital: "기준 자금 1,000만원 · 최대 3종목 · 5분 판단",
  error: "모의투자를 시작하지 못했어요. 잠시 후 다시 시도해 주세요.",
  note: "실제 주문은 발생하지 않으며, 수집 데이터는 향후 판단·추천 오답노트로 사용해요.",
} as const;
